heat_template_version: 2014-10-16

description: >
  Create GPT formatted virtual block devices for development

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: init_disk}

  init_disk:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: init_disk.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}